### ISSUE TITLE
Tube numbering inconsistent in places

### ISSUE THREAD

**Issue by magoorden** [DEIS-Tools/CLAIRE-library#24]
For setting water levels in tubes, we currently have the following command

```
 5 <tube> <level>;   - Set tube level in millimeters.
   <tube> = {1: TUBE0, 2: TUBE1}
```

This shows that the command starts counting from 1, but the underlying naming from 0. This is inconsistent and might result in errors when using it, i.e., a user might want to change the level in tube 1 using `5 1 xx`, wrongly changing the levels of tube 0.

I suggest to keep the command and change the naming, as everyone else except computer scientist start counting at 1.

**Comment by falkecarlsen** [comment]
Agreed. I changed my mind on indexing during development, due to the ergonomics of hitting 0 and 1 resp. on a number-row being poorer than 1 and 2.
