### ISSUE TITLE
[Physical setup] Add gaps for air to escape on top of the tube

### ISSUE THREAD

**Issue by magoorden** [DEIS-Tools/CLAIRE-library#41]
With the sensors in place, air can enter and escape through the overflow tube. But once overflow is reached, this air opening is lost and outflow through the overflow tube takes some time to start flowing.

**Comment by falkecarlsen** [comment]
Resolved today. However issue persists.
I believe proper flow only happens when overflow tube is completely filled, and siphoning beings, quickly emptying the overfilled tube. 
Hereafter, exiting water creates a suctioning effect which keeps the tube empty regardless of inflow duty cycle.
